### ISSUE TITLE
Proposal peer review - Team Uchihas

### ISSUE THREAD

**Issue by vsatyamuralikrishna** [INFO-526-F24/project-01-MintMindsForDataViz#3]
The following is the peer review of the project proposal by Team Uchihas. The team members that participated in this review are 

- [Venkata Satya Murali Krishna] - @satya131113
- [Jayant Biradar] - @Chromaniquej1
- [Harsh Wasnik] - @wasnikh0
- [Spoorthy Nagendra] - @SpoorthyNagendra
- [Abhighyan] - @Abhighyan9

- Describe the goal of the project.
  *The project description is not mentioned making it difficult to comprehend the goal of the project.*

- Describe the data used or collected.
    * Original data curator and collection process in not mentioned*

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
  *Detailed analysis plan is missing and precise methodology for the analysis is not mentioned*

- Is there anything that is unclear from the proposal?
 *Project Titile is missing*
 *Project Description is missing*
 *Original data curator and collection process in not mentioned*
 *Target population was not mentioned*
 *Originality of the question is not discussed*
 *Reason for question selection is not mentioned in two datasets (Amazon Sales Report dataset and Olympic Dataset)*
 *Work Flow is missing*

- Provide constructive feedback on how the team might be able to improve their project.
  To strengthen the project, it would be helpful to provide more context on the data source, collection process, and target audience. Clarifying the reasoning behind the selected research questions would also add value. Outlining the workflow and adding a general description of the methods and tools used would make the approach clearer. Including an analysis plan with key steps would enhance the structure of the project. Lastly, updating the project and proposal with clearer titles and descriptions would help better convey the project's focus and goals.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We are most interested in the reasoning behind the chosen research questions and the workflow, as they highlight the project's direction and execution.

- Provide constructive feedback on any issues with file and/or code organization.
No feedback on the file/code organisation

- (Optional) Any further comments or feedback?

**Comment by rajamalireddy** [comment]
Thank you for the feedback. We addressed this during the project implementation.
